[package]
name = "server_common"
version = "0.1.0"
authors = ["bgxjordan"]
edition = "2018"

[dependencies]
async-trait = "0.1.36"
bytes = "0.5"
tokio = { version = "0.2", features = ["full"] }
to_vec = "0.1"